services:
  postgres:
    image: postgres:15
    # container_name: oficina_postgres
    container_name: oficina_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: OficinaDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SuaSenha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: oficina_api:latest
    # container_name: oficina_api
    container_name: oficina_api
    depends_on:
      postgres:
        condition: service_healthy
      mailhog:
        condition: service_started
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=OficinaDB;Username=postgres;Password=SuaSenha
      - EmailSettings__SmtpServer=mailhog
      - EmailSettings__Port=1025
      - EmailSettings__UseSSL=false
      - EmailSettings__From=noreply@oficinamecanica.com
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    container_name: oficina_mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Interface Web UI
    restart: unless-stopped

  sonarqube:
    image: sonarqube:community
    container_name: oficina_sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: unless-stopped

volumes:
  postgres_data: {}
  sonarqube_data: {}
  sonarqube_logs: {}
  sonarqube_extensions: {}