apiVersion: v1
kind: Service
metadata:
  name: oficina-api-service
  namespace: oficina-mecanica
spec:
  selector:
    app: oficina-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oficina-ingress
  namespace: oficina-mecanica
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: oficina.mecanica.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oficina-api-service
                port:
                  number: 80
