apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-config
  namespace: oficina-mecanica
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  EmailSettings__SmtpServer: "smtp.seuprovedor.com"
  EmailSettings__Port: "587"
  EmailSettings__UseSSL: "true"
  EmailSettings__From: "noreply@oficinamecanica.com"
  Jwt__Issuer: "mecanica-api"
  Jwt__Audience: "mecanica-cliente"
  Jwt__ExpiracaoMinutos: "60"
