apiVersion: v1
kind: Secret
metadata:
  name: oficina-secrets
  namespace: oficina-mecanica
type: Opaque
data:
  # echo -n "SuaSenha" | base64
  POSTGRES_PASSWORD: U3VhU2VuaGE=
  # echo -n "mecanica-jwt-secret-key-minimo-32-chars!!" | base64
  JWT_SECRET_KEY: bWVjYW5pY2Etand0LXNlY3JldC1rZXktbWluaW1vLTMyLWNoYXJzISE=
  # echo -n "K7mP2nQx9vR4wL8sY1tZ6uA3cE5gJ0hF" | base64
  PASSWORD_KEY: SzdtUDJuUXg5dlI0d0w4c1kxdFo2dUEzY0U1Z0owaEY=
  # sem credenciais SMTP configuradas no ambiente de desenvolvimento
  EMAIL_USERNAME: ""
  EMAIL_PASSWORD: ""
