apiVersion: v1
kind: Secret
metadata:
  name: oficina-mecanica-secret
type: Opaque
stringData:
  Jwt__SecretKey: "oficina-mecanica-jwt-secret-key-fase2-2025!!"
  Seguranca__PasswordKey: "oficina-password-key-fase2"
  PostgresPassword: "oficina123"
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=OficinaDB;Username=postgres;Password=oficina123"
